networks:
  asgard:
    external: true

services:
  thor:
    container_name: thor
    build:
      context: .
      dockerfile: docker/thor.dockerfile
    volumes:
      - .:/var/www/html/thor
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - asgard
    command: composer thor-api

  postgres:
    container_name: odin
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: odin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - asgard